// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAsr3BLGtICglpn4Ka5Y8B3C_XQ2EJr5A',
    appId: '1:286291747056:web:d966611815740b27b52235',
    messagingSenderId: '286291747056',
    projectId: 'studentcareerguidance-e2d28',
    authDomain: 'studentcareerguidance-e2d28.firebaseapp.com',
    storageBucket: 'studentcareerguidance-e2d28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCThLelGc82GFDZcDkn1eA6eNwrHqfkLU',
    appId: '1:286291747056:android:5eb2bad7f1ada570b52235',
    messagingSenderId: '286291747056',
    projectId: 'studentcareerguidance-e2d28',
    storageBucket: 'studentcareerguidance-e2d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSNUM5h_YIzyzjHrbFrMd9Cirm9EgN20',
    appId: '1:286291747056:ios:d602afcc88de8938b52235',
    messagingSenderId: '286291747056',
    projectId: 'studentcareerguidance-e2d28',
    storageBucket: 'studentcareerguidance-e2d28.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAsr3BLGtICglpn4Ka5Y8B3C_XQ2EJr5A',
    appId: '1:286291747056:web:d966611815740b27b52235',
    messagingSenderId: '286291747056',
    projectId: 'studentcareerguidance-e2d28',
    authDomain: 'studentcareerguidance-e2d28.firebaseapp.com',
    storageBucket: 'studentcareerguidance-e2d28.firebasestorage.app',
  );
}
